import "./functions/bootstrap.js";
import "./functions/availability.js";
import "./functions/assets.js";
import "./functions/stock.js";
import "./functions/products.js";
import "./functions/directory.js";
import "./functions/quotes.js";
import "./functions/scan.js";
import "./functions/reports.js";
